name: college_bus_tracker
description: A new Flutter project for college bus tracking.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ GOOGLE MAPS
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.2.0

  # ðŸ”¹ Notifications Package
  flutter_local_notifications: ^18.0.1 

  # ðŸ”¹ Date Formatting
  intl: ^0.19.0

  cupertino_icons: ^1.0.6

  # Geolocator
  geolocator: ^13.0.0

  # WebSocket (Optional)
  web_socket_channel: ^3.0.0

  # Firebase packages
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  google_places_flutter: ^2.1.1
  flutter_polyline_points: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/home.png