name: college_bus_tracker
description: A new Flutter project for college bus tracking.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # OpenStreetMap client
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

  # Geolocator
  geolocator: ^12.0.0

  # ðŸ”¹ WebSocket (ESP32 integration)  â† ADD THIS
  web_socket_channel: ^2.4.0

  # Firebase packages
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/home.png
